name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv/bin/pip install -r requirements_test.txt
      - name: Test with pytest
        run: |
          venv/bin/python -m pytest tests/